name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build

      - name: Setup Environment For Tests
        run: |
          cp .env.example .env
          sed -i '/^DB_CONNECTION=/s/=.*/=sqlite/' .env
          sed -i '/^DB_DATABASE=/s/=.*/=:memory:/' .env
          echo "APP_KEY=" >> .env
          php artisan key:generate --ansi
          echo "APP_ENV=testing" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "LOG_CHANNEL=stderr" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Execute Pest Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: ./vendor/bin/pest --ci